### ISSUE TITLE
JLC PCB fabrication instructions no longer work

### ISSUE THREAD

**Issue by eduardkieser** [simplefoc/Arduino-SimpleFOCShield#11]
I followed the steps described [here](https://www.youtube.com/watch?v=sax_9sUgBuk&t=585s&ab_channel=simplefoc) with version 2.0.4:

but after specifying the bom and pick&place file, I get the following error:
```
File processing failed, please check your file and upload again.
```

I also tried with 2.0 is there an update to the procedure to remain compatible with JLC PCB?

**Comment by askuric** [comment]
Hmm, they mush have changed the bom format. 
There is probably a different order/naming of columns in the BOM files. The pick and place document should be fine probably. 
I'll try to look into it in the next days.

**Comment by askuric** [comment]
Hi @eduardkieser,

Thanks for reporting this!
I've just checked and JLCPCB has changed a lot of their requirements for the fabrication files since I've ordered last shields. :D
The new BOM and CPL files are in available in the repo. 

You might have to hurry up because there are just 24 L6234 available in the jlcpcb parts as of today (22/06/2024) :D

**Comment by eduardkieser** [comment]
@askuric Thanks so much!
Will take a look as soon as I get a moment.

**Comment by eduardkieser** [comment]
Tested last night. Works beautifully, thanks! closing.
