### ISSUE TITLE
Header pins too tall?

### ISSUE THREAD

**Issue by steph643** [simplefoc/Arduino-SimpleFOCShield#5]
On the left, a nucleao-64 with its 8mm pins. On the right, my brand new SimpleFOCShield with its 18.5mm pins, which cannot penetrate fully into the 9mm Arduino header.
![image](https://user-images.githubusercontent.com/7039479/121247134-2e2eac80-c8a2-11eb-98c7-d1eed1d69871.png)
![image](https://user-images.githubusercontent.com/7039479/121247039-10614780-c8a2-11eb-82e4-47ff54dba78c.png)
Is it unintended or am I missing something?

**Comment by askuric** [comment]
Yep, i think the idea is the clearance. But to be honest I'm not sure. :D
These are the original Arduino headers, from the arduino.cc
I guess, if you really lack the space you can cut them off.

I've done few iterations over different manufacturers, and due to the great lack of parts at present, these were the best choice. 

Honestly, I like them a lot, but you're tight that they take much more space.

I've pivoted from them, for the newest batch though. Even they were out of stock 🤣

**Comment by steph643** [comment]
> I've pivoted from them, for the newest batch though. Even they were out of stock

I'm fighting to find the same kind of connector (in double-row). Would you disclose who your supplier is?

**Comment by askuric** [comment]
Hey @steph643,
I've tried many of them and I am buying them online from the webshops as well. Because my quantities are small.

So I've started with the mouser, where I've bought every component separately. But they soon ran out of the components. 
Then I've bought them from spark fun. But they too ran out.
Then Arduino webshop.
The last one I've bought was from afafruit. 

And then even the other components disappeared from the market 😃
